version: '3.8'

services:
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "8085:80"  # Acceso directo (opcional)
  
  nginx-web:
    image: nginx
    container_name: web
    volumes:
      - ./web:/usr/share/nginx/html:ro
    restart: always

  proxy:
    image: nginx
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - phpmyadmin
      - nginx-web

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: lsi
      MYSQL_PASSWORD: lsi
    volumes:
      - db_data:/var/lib/mysql

  dummy-docker:
    image: httpd
    container_name: dummy-docker

volumes:
  db_data: